// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZfHMPPMTWxAnSpELmMaKs1LeX5tI167Y',
    appId: '1:342781458764:web:ae7c28036fdab8de7d37e9',
    messagingSenderId: '342781458764',
    projectId: 'bee-threads-v1',
    authDomain: 'bee-threads-v1.firebaseapp.com',
    storageBucket: 'bee-threads-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3uUfJ1IA9fy-bXKrcfQl4NYzWI5CvvU',
    appId: '1:342781458764:android:d74f88b5e57cc0e37d37e9',
    messagingSenderId: '342781458764',
    projectId: 'bee-threads-v1',
    storageBucket: 'bee-threads-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTivg7wzUyvJQZZuQFvIWcneAGGf5-7Jo',
    appId: '1:342781458764:ios:312f93671de54d5e7d37e9',
    messagingSenderId: '342781458764',
    projectId: 'bee-threads-v1',
    storageBucket: 'bee-threads-v1.appspot.com',
    iosBundleId: 'com.example.threads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTivg7wzUyvJQZZuQFvIWcneAGGf5-7Jo',
    appId: '1:342781458764:ios:312f93671de54d5e7d37e9',
    messagingSenderId: '342781458764',
    projectId: 'bee-threads-v1',
    storageBucket: 'bee-threads-v1.appspot.com',
    iosBundleId: 'com.example.threads',
  );
}
